# Generated by Django 4.1.3 on 2022-12-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("data_added", models.DateTimeField(auto_now_add=True)),
                ("data_updated", models.DateTimeField(auto_now=True)),
                ("urls", models.SlugField()),
                ("is_active", models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=50, verbose_name="SUSYS"),
        ),
    ]
